#!/bin/bash
GHA_DB_BULK_SIZE=5 GHA_NO_GHA_MAP=1 GHA_ES_BULK_SIZE=500 GHA_NO_INCREMENTAL='' GHA_DEBUG='' GHA_LOAD_CONFIG='' GHA_SAVE_CONFIG='' GHA_HOUR_FROM=0 GHA_HOUR_TO=23 GHA_DAY_FROM='2020-10-01' GHA_DAY_TO='2020-10-03' GHA_ES_URL="`cat ES_URL.prod.secret`" GHA_DB_CONN="`cat DB_CONN.prod.secret`" GHA_GITHUB_OAUTH="`cat /etc/github/oauths`" ./dadsgha ./vitess/
